services:
  urilix.api:
    image: ${DOCKER_REGISTRY-}urilixapi
    build:
      context: .
      dockerfile: src/UriLix.API/Dockerfile
    container_name: urilix.api
  urilix.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword123
    volumes:
      - urilix:/var/opt/mssql
    ports:
      - "1433:1433"
    container_name: urilix.database
volumes:
  urilix:  